  
name: Deploy Website

on: [push]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install # will run `yarn install` command
        
    - name: Build React App
      run: yarn build
      
    - name: Install Surge
      run: npm install --global surge

    - name: Deploy to Surge
      run: surge ./build bootcamp_assmt2.surge.sh --token ${{ secrets.SURGE_TOKEN }}
